### ISSUE TITLE
Test status not updated when running multiple tests

### ISSUE THREAD

**Issue by khkiley** [connor4312/nodejs-testing#6]
I have multiple tests in the project directory structure. I select the button to run all tests, and can see in the output that they are run, but the test runner window on the left does not reflect that, And the status says "0/0 tests passed (0.00%)"

When running the tests individually the status updates correctly for the tests and the parent directory.

Thanks

**Comment by connor4312** [comment]
What version of VS Code are you using?

**Comment by khkiley** [comment]
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by connor4312** [comment]
I'm not able to repro this. Can you click the "Show Output" button and share the info from the console window?

**Comment by khkiley** [comment]
While the window does not update:

***@***.***

Its looks like everything is running:


worker1> starting c:\Node\brick-city\utility\src\zeroPaddedBinary\test.js
worker2> starting c:\Node\brick-city\utility\src\mssqlCdcUpdateMaskTo\test.js
worker3> starting c:\Node\brick-city\utility\src\isUndefinedOrNull\test.js
worker4> starting c:\Node\brick-city\utility\src\isRegex\test.js
worker1> TAP version 13
worker1> # Subtest: zeroPaddedBinary
worker1>     # Subtest: 7 should return '0b00000111'
worker1>     ok 1 - 7 should return '0b00000111'
worker1>       ---
worker1>       duration_ms: 0.9112
worker1>       ...
worker1>     # Subtest: 262 should return '0b0000000100000110'
worker1>     ok 2 - 262 should return '0b0000000100000110'
worker1>       ---
worker1>       duration_ms: 0.3099
worker1>       ...
worker1>     # Subtest: null should throw because it is not of type number
worker1>     ok 3 - null should throw because it is not of type number
worker1>       ---
worker1>       duration_ms: 2.3836
worker1>       ...
worker1>     # Subtest: undefined should throw because it is not of type number
worker1>     ok 4 - undefined should throw because it is not of type number
worker1>       ---
worker1>       duration_ms: 2.3042
worker1>       ...
worker1>     # Subtest: '5' should throw because it is not of type number (Does not coerce)
worker1>     ok 5 - '5' should throw because it is not of type number (Does not coerce)
worker1>       ---
worker1>       duration_ms: 0.5281
worker1>       ...
worker1>     1..5
worker1> ok 1 - zeroPaddedBinary
worker1>   ---
worker1>   duration_ms: 10.8728
worker1>   type: 'suite'
worker1>   ...
worker1> 1..1
worker1> # tests 5
worker1> # suites 1
worker1> # pass 5
worker1> # fail 0
worker1> # cancelled 0
worker1> # skipped 0
worker1> # todo 0
worker1> # duration_ms 48.4138
worker1> starting c:\Node\brick-city\utility\src\isPlainObjectEmpty\test.js
worker2> TAP version 13
worker2> # Subtest: updateMaskToBooleanArray
worker2>     # Subtest: 5 should throw TypeError('Expecting a buffer'), as 5 is not a buffer
worker2>     ok 1 - 5 should throw TypeError('Expecting a buffer'), as 5 is not a buffer
worker2>       ---
worker2>       duration_ms: 2.9881
worker2>       ...
worker3> TAP version 13
worker2>     1..1
worker2> ok 1 - updateMaskToBooleanArray
worker2>   ---
worker2>   duration_ms: 8.072
worker2>   type: 'suite'
worker2>   ...
worker3> # Subtest: isUndefinedOrNull
worker2> # Subtest: updateMaskToBitArray
worker2>     # Subtest: 5 should throw TypeError('Expecting a buffer'), as 5 is not a buffer
worker2>     ok 1 - 5 should throw TypeError('Expecting a buffer'), as 5 is not a buffer
worker3>     # Subtest: null is undefined or null
worker3>     ok 1 - null is undefined or null
worker2>       ---
worker2>       duration_ms: 0.6498
worker2>       ...
worker3>       ---
worker3>       duration_ms: 1.0085
worker3>       ...
worker2>     1..1
worker2> ok 2 - updateMaskToBitArray
worker3>     # Subtest: undefined is undefined or null
worker3>     ok 2 - undefined is undefined or null
worker3>       ---
worker3>       duration_ms: 0.2069
worker3>       ...
worker2>   ---
worker2>   duration_ms: 0.9719
worker2>   type: 'suite'
worker2>   ...
worker3>     # Subtest: {} is not undefined or null
worker3>     ok 3 - {} is not undefined or null
worker3>       ---
worker3>       duration_ms: 0.1773
worker3>       ...
worker2> # Subtest: updateMaskToBooleanArray - individual bits
worker2>     # Subtest: 0b00000000  should resolve to [ , false, false, false, false, false, false, false, false]
worker2>     ok 1 - 0b00000000  should resolve to [ , false, false, false, false, false, false, false, false]
worker2>       ---
worker2>       duration_ms: 1.5956
worker2>       ...
worker3>     # Subtest: [] is not undefined or null
worker3>     ok 4 - [] is not undefined or null
worker3>       ---
worker3>       duration_ms: 0.2214
worker3>       ...
worker2>     # Subtest: 0b00000001  should resolve to [ , true, false, false, false, false, false, false, false]
worker2>     ok 2 - 0b00000001  should resolve to [ , true, false, false, false, false, false, false, false]
worker2>       ---
worker2>       duration_ms: 0.2073
worker2>       ...
worker2>     # Subtest: 0b00000010  should resolve to [ , false, true, false, false, false, false, false, false]
worker2>     ok 3 - 0b00000010  should resolve to [ , false, true, false, false, false, false, false, false]
worker3>     1..4
worker3> ok 1 - isUndefinedOrNull
worker3>   ---
worker3>   duration_ms: 7.5289
worker3>   type: 'suite'
worker3>   ...
worker2>       ---
worker2>       duration_ms: 0.1709
worker2>       ...
worker2>     # Subtest: 0b00000100  should resolve to [ , false, false, true, false, false, false, false, false]
worker2>     ok 4 - 0b00000100  should resolve to [ , false, false, true, false, false, false, false, false]
worker2>       ---
worker2>       duration_ms: 0.3096
worker2>       ...
worker2>     # Subtest: 0b00001000  should resolve to [ , false, false, false, true, false, false, false, false]
worker2>     ok 5 - 0b00001000  should resolve to [ , false, false, false, true, false, false, false, false]
worker2>       ---
worker2>       duration_ms: 0.1886
worker2>       ...
worker2>     # Subtest: 0b00010000  should resolve to [ , false, false, false, false, true, false, false, false]
worker2>     ok 6 - 0b00010000  should resolve to [ , false, false, false, false, true, false, false, false]
worker2>       ---
worker2>       duration_ms: 0.3234
worker2>       ...
worker2>     # Subtest: 0b00100000  should resolve to [ , false, false, false, false, false, true, false, false]
worker2>     ok 7 - 0b00100000  should resolve to [ , false, false, false, false, false, true, false, false]
worker2>       ---
worker2>       duration_ms: 0.2309
worker2>       ...
worker2>     # Subtest: 0b01000000  should resolve to [ , false, false, false, false, false, false, true, false]
worker2>     ok 8 - 0b01000000  should resolve to [ , false, false, false, false, false, false, true, false]
worker2>       ---
worker2>       duration_ms: 0.2626
worker2>       ...
worker3> 1..1
worker3> # tests 4
worker2>     # Subtest: 0b10000000  should resolve to [ , false, false, false, false, false, false, false, true]
worker2>     ok 9 - 0b10000000  should resolve to [ , false, false, false, false, false, false, false, true]
worker3> # suites 1
worker2>       ---
worker2>       duration_ms: 0.2757
worker2>       ...
worker3> # pass 4
worker3> # fail 0
worker2>     1..9
worker3> # cancelled 0
worker2> ok 3 - updateMaskToBooleanArray - individual bits
worker3> # skipped 0
worker2>   ---
worker2>   duration_ms: 6.4612
worker2>   type: 'suite'
worker2>   ...
worker3> # todo 0
worker2> # Subtest: updateMaskToBooleanArray multiple bits
worker2>     # Subtest: 0b11111111  should resolve to [ , true, true, true, true, true, true, true, true]
worker2>     ok 1 - 0b11111111  should resolve to [ , true, true, true, true, true, true, true, true]
worker2>       ---
worker2>       duration_ms: 0.6404
worker2>       ...
worker2>     # Subtest: 0b11111101  should resolve to [ , true, false, true, true, true, true, true, true]
worker2>     ok 2 - 0b11111101  should resolve to [ , true, false, true, true, true, true, true, true]
worker4> TAP version 13
worker2>       ---
worker2>       duration_ms: 0.3199
worker2>       ...
worker2>     # Subtest: 0b11111011  should resolve to [ , true, true, false, true, true, true, true, true]
worker2>     ok 3 - 0b11111011  should resolve to [ , true, true, false, true, true, true, true, true]
worker2>       ---
worker2>       duration_ms: 0.2447
worker2>       ...
worker3> # duration_ms 45.4933
worker2>     # Subtest: 0b11110111  should resolve to [ , true, true, true, false, true, true, true, true]
worker2>     ok 4 - 0b11110111  should resolve to [ , true, true, true, false, true, true, true, true]
worker2>       ---
worker2>       duration_ms: 0.2326
worker2>       ...
worker4> # Subtest: isRegex
worker2>     # Subtest: 0b11101111  should resolve to [ , true, true, true, true, false, true, true, true]
worker2>     ok 5 - 0b11101111  should resolve to [ , true, true, true, true, false, true, true, true]
worker2>       ---
worker2>       duration_ms: 0.2431
worker2>       ...
worker2>     # Subtest: 0b11011111  should resolve to [ , true, true, true, true, true, false, true, true]
worker2>     ok 6 - 0b11011111  should resolve to [ , true, true, true, true, true, false, true, true]
worker2>       ---
worker2>       duration_ms: 0.2511
worker2>       ...
worker2>     # Subtest: 0b10111111  should resolve to [ , true, true, true, true, true, true, false, true]
worker2>     ok 7 - 0b10111111  should resolve to [ , true, true, true, true, true, true, false, true]
worker2>       ---
worker2>       duration_ms: 0.2477
worker2>       ...
worker4>     # Subtest: null is not a regular expression
worker4>     ok 1 - null is not a regular expression
worker2>     # Subtest: 0b01111111  should resolve to [ , true, true, true, true, true, true, true, false]
worker2>     ok 8 - 0b01111111  should resolve to [ , true, true, true, true, true, true, true, false]
worker4>       ---
worker4>       duration_ms: 1.7341
worker4>       ...
worker2>       ---
worker2>       duration_ms: 0.3078
worker2>       ...
worker2>     1..8
worker2> ok 4 - updateMaskToBooleanArray multiple bits
worker2>   ---
worker2>   duration_ms: 3.3012
worker2>   type: 'suite'
worker2>   ...
worker4>     # Subtest: undefined is not a regular expression
worker4>     ok 2 - undefined is not a regular expression
worker2> # Subtest: updateMaskToBooleanArray multiple bytes
worker4>       ---
worker4>       duration_ms: 2.453
worker4>       ...
worker2>     # Subtest: 0b00000001 0b11111111  should resolve to [ , true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false]
worker2>     ok 1 - 0b00000001 0b11111111  should resolve to [ , true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false]
worker2>       ---
worker2>       duration_ms: 0.4054
worker2>       ...
worker2>     # Subtest: 0b00000101 0b00000001 0b11111111  should resolve to [ , true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false]
worker2>     ok 2 - 0b00000101 0b00000001 0b11111111  should resolve to [ , true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false]
worker4>     # Subtest: {} is not a regular expression
worker4>     ok 3 - {} is not a regular expression
worker2>       ---
worker2>       duration_ms: 0.2289
worker2>       ...
worker2>     1..2
worker4>       ---
worker4>       duration_ms: 0.3963
worker4>       ...
worker2> ok 5 - updateMaskToBooleanArray multiple bytes
worker2>   ---
worker2>   duration_ms: 0.9103
worker2>   type: 'suite'
worker2>   ...
worker2> # Subtest: updateMaskToBitArray - individual bits
worker2>     # Subtest: 0b00000000  should resolve to [ , 0, 0, 0, 0, 0, 0, 0, 0]
worker2>     ok 1 - 0b00000000  should resolve to [ , 0, 0, 0, 0, 0, 0, 0, 0]
worker2>       ---
worker2>       duration_ms: 0.4543
worker2>       ...
worker4>     # Subtest: 'Test' is not a regular expression
worker4>     ok 4 - 'Test' is not a regular expression
worker2>     # Subtest: 0b00000001  should resolve to [ , 1, 0, 0, 0, 0, 0, 0, 0]
worker2>     ok 2 - 0b00000001  should resolve to [ , 1, 0, 0, 0, 0, 0, 0, 0]
worker4>       ---
worker4>       duration_ms: 0.3831
worker4>       ...
worker2>       ---
worker2>       duration_ms: 0.249
worker2>       ...
worker4>     # Subtest: {test: 'a'} is not an regular expression
worker4>     ok 5 - {test: 'a'} is not an regular expression
worker3> starting c:\Node\brick-city\utility\src\isPlainObject\test.js
worker2>     # Subtest: 0b00000010  should resolve to [ , 0, 1, 0, 0, 0, 0, 0, 0]
worker2>     ok 3 - 0b00000010  should resolve to [ , 0, 1, 0, 0, 0, 0, 0, 0]
worker2>       ---
worker2>       duration_ms: 0.2076
worker2>       ...
worker2>     # Subtest: 0b00000100  should resolve to [ , 0, 0, 1, 0, 0, 0, 0, 0]
worker2>     ok 4 - 0b00000100  should resolve to [ , 0, 0, 1, 0, 0, 0, 0, 0]
worker2>       ---
worker2>       duration_ms: 0.2704
worker2>       ...
worker2>     # Subtest: 0b00001000  should resolve to [ , 0, 0, 0, 1, 0, 0, 0, 0]
worker2>     ok 5 - 0b00001000  should resolve to [ , 0, 0, 0, 1, 0, 0, 0, 0]
worker2>       ---
worker2>       duration_ms: 0.2172
worker2>       ...
worker2>     # Subtest: 0b00010000  should resolve to [ , 0, 0, 0, 0, 1, 0, 0, 0]
worker2>     ok 6 - 0b00010000  should resolve to [ , 0, 0, 0, 0, 1, 0, 0, 0]
worker2>       ---
worker2>       duration_ms: 0.2562
worker2>       ...
worker2>     # Subtest: 0b00100000  should resolve to [ , 0, 0, 0, 0, 0, 1, 0, 0]
worker2>     ok 7 - 0b00100000  should resolve to [ , 0, 0, 0, 0, 0, 1, 0, 0]
worker2>       ---
worker2>       duration_ms: 0.1759
worker2>       ...
worker2>     # Subtest: 0b01000000  should resolve to [ , 0, 0, 0, 0, 0, 0, 1, 0]
worker2>     ok 8 - 0b01000000  should resolve to [ , 0, 0, 0, 0, 0, 0, 1, 0]
worker2>       ---
worker2>       duration_ms: 0.17
worker2>       ...
worker2>     # Subtest: 0b10000000  should resolve to [ , 0, 0, 0, 0, 0, 0, 0, 1]
worker2>     ok 9 - 0b10000000  should resolve to [ , 0, 0, 0, 0, 0, 0, 0, 1]
worker2>       ---
worker2>       duration_ms: 0.3456
worker2>       ...
worker2>     1..9
worker2> ok 6 - updateMaskToBitArray - individual bits
worker2>   ---
worker2>   duration_ms: 2.8541
worker2>   type: 'suite'
worker2>   ...
worker2> # Subtest: updateMaskToBitArray multiple bits
worker2>     # Subtest: 0b11111111  should resolve to [ , 1, 1, 1, 1, 1, 1, 1, 1]
worker2>     ok 1 - 0b11111111  should resolve to [ , 1, 1, 1, 1, 1, 1, 1, 1]
worker2>       ---
worker2>       duration_ms: 0.5378
worker2>       ...
worker2>     # Subtest: 0b11111101  should resolve to [ , 1, 0, 1, 1, 1, 1, 1, 1]
worker2>     ok 2 - 0b11111101  should resolve to [ , 1, 0, 1, 1, 1, 1, 1, 1]
worker2>       ---
worker2>       duration_ms: 0.2681
worker2>       ...
worker2>     # Subtest: 0b11111011  should resolve to [ , 1, 1, 0, 1, 1, 1, 1, 1]
worker2>     ok 3 - 0b11111011  should resolve to [ , 1, 1, 0, 1, 1, 1, 1, 1]
worker2>       ---
worker2>       duration_ms: 0.1732
worker2>       ...
worker2>     # Subtest: 0b11110111  should resolve to [ , 1, 1, 1, 0, 1, 1, 1, 1]
worker2>     ok 4 - 0b11110111  should resolve to [ , 1, 1, 1, 0, 1, 1, 1, 1]
worker2>       ---
worker2>       duration_ms: 0.1905
worker2>       ...
worker2>     # Subtest: 0b11101111  should resolve to [ , 1, 1, 1, 1, 0, 1, 1, 1]
worker2>     ok 5 - 0b11101111  should resolve to [ , 1, 1, 1, 1, 0, 1, 1, 1]
worker2>       ---
worker2>       duration_ms: 0.235
worker2>       ...
worker2>     # Subtest: 0b11011111  should resolve to [ , 1, 1, 1, 1, 1, 0, 1, 1]
worker2>     ok 6 - 0b11011111  should resolve to [ , 1, 1, 1, 1, 1, 0, 1, 1]
worker2>       ---
worker2>       duration_ms: 0.1782
worker2>       ...
worker2>     # Subtest: 0b10111111  should resolve to [ , 1, 1, 1, 1, 1, 1, 0, 1]
worker2>     ok 7 - 0b10111111  should resolve to [ , 1, 1, 1, 1, 1, 1, 0, 1]
worker2>       ---
worker2>       duration_ms: 0.1888
worker2>       ...
worker2>     # Subtest: 0b01111111  should resolve to [ , 1, 1, 1, 1, 1, 1, 1, 0]
worker2>     ok 8 - 0b01111111  should resolve to [ , 1, 1, 1, 1, 1, 1, 1, 0]
worker2>       ---
worker2>       duration_ms: 0.2526
worker2>       ...
worker2>     1..8
worker2> ok 7 - updateMaskToBitArray multiple bits
worker2>   ---
worker2>   duration_ms: 2.5814
worker2>   type: 'suite'
worker2>   ...
worker2> # Subtest: updateMaskToBitArray multiple bytes
worker2>     # Subtest: 0b00000001 0b11111111  should resolve to [ , 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
worker2>     ok 1 - 0b00000001 0b11111111  should resolve to [ , 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
worker2>       ---
worker2>       duration_ms: 0.4611
worker2>       ...
worker2>     # Subtest: 0b00000101 0b00000001 0b11111111  should resolve to [ , 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0]
worker2>     ok 2 - 0b00000101 0b00000001 0b11111111  should resolve to [ , 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0]
worker2>       ---
worker2>       duration_ms: 0.1422
worker2>       ...
worker2>     1..2
worker2> ok 8 - updateMaskToBitArray multiple bytes
worker2>   ---
worker2>   duration_ms: 0.9584
worker2>   type: 'suite'
worker2>   ...
worker2> 1..8
worker2> # tests 40
worker2> # suites 8
worker2> # pass 40
worker2> # fail 0
worker2> # cancelled 0
worker2> # skipped 0
worker2> # todo 0
worker2> # duration_ms 136.8294
worker4>       ---
worker4>       duration_ms: 0.3439
worker4>       ...
worker4>     # Subtest: 55 is not an regular expression
worker4>     ok 6 - 55 is not an regular expression
worker4>       ---
worker4>       duration_ms: 0.3251
worker4>       ...
worker4>     # Subtest: [] is not a regular expression
worker4>     ok 7 - [] is not a regular expression
worker4>       ---
worker4>       duration_ms: 0.3645
worker4>       ...
worker4>     # Subtest: [1,2] is not a regular expression
worker4>     ok 8 - [1,2] is not a regular expression
worker4>       ---
worker4>       duration_ms: 0.4371
worker4>       ...
worker4>     # Subtest: ()=>{} is not a regular expression
worker4>     ok 9 - ()=>{} is not a regular expression
worker4>       ---
worker4>       duration_ms: 0.4209
worker4>       ...
worker4>     # Subtest: /(?:)/ is a regular expression
worker4>     ok 10 - /(?:)/ is a regular expression
worker4>       ---
worker4>       duration_ms: 0.5191
worker4>       ...
worker4>     # Subtest: /.+/ is a regular expression
worker4>     ok 11 - /.+/ is a regular expression
worker4>       ---
worker4>       duration_ms: 0.3694
worker4>       ...
worker4>     # Subtest: new RegExp("ab+c") is a regular expression
worker4>     ok 12 - new RegExp("ab+c") is a regular expression
worker4>       ---
worker4>       duration_ms: 0.3146
worker4>       ...
worker4>     # Subtest: new RegExp('') is a regular expression
worker4>     ok 13 - new RegExp('') is a regular expression
worker4>       ---
worker4>       duration_ms: 0.3774
worker4>       ...
worker4>     1..13
worker4> ok 1 - isRegex
worker4>   ---
worker4>   duration_ms: 15.5291
worker4>   type: 'suite'
worker4>   ...
worker4> 1..1
worker4> # tests 13
worker4> # suites 1
worker4> # pass 13
worker4> # fail 0
worker4> # cancelled 0
worker4> # skipped 0
worker4> # todo 0
worker4> # duration_ms 67.4988
worker4> starting c:\Node\brick-city\utility\src\deepFreeze\test.js
worker2> starting c:\Node\brick-city\utility\src\arrayToString\test.js
worker1> TAP version 13
worker1> # Subtest: isPlainObjectEmpty
worker1>     # Subtest: null is not an empty plain object
worker1>     ok 1 - null is not an empty plain object
worker1>       ---
worker1>       duration_ms: 0.9022
worker1>       ...
worker1>     # Subtest: undefined is not an empty plain object
worker1>     ok 2 - undefined is not an empty plain object
worker1>       ---
worker1>       duration_ms: 0.22
worker1>       ...
worker1>     # Subtest: {} is an empty plain object
worker1>     ok 3 - {} is an empty plain object
worker1>       ---
worker1>       duration_ms: 0.1835
worker1>       ...
worker1>     # Subtest: {test: 'a'} is not an empty plain object
worker1>     ok 4 - {test: 'a'} is not an empty plain object
worker1>       ---
worker1>       duration_ms: 0.2252
worker1>       ...
worker1>     # Subtest: [] is not an empty plain object
worker1>     ok 5 - [] is not an empty plain object
worker1>       ---
worker1>       duration_ms: 0.2176
worker1>       ...
worker1>     # Subtest: [1,2] is not an empty plain object
worker1>     ok 6 - [1,2] is not an empty plain object
worker1>       ---
worker1>       duration_ms: 0.1762
worker1>       ...
worker1>     # Subtest: ()=>{} is not an empty plain object
worker1>     ok 7 - ()=>{} is not an empty plain object
worker1>       ---
worker1>       duration_ms: 0.171
worker1>       ...
worker1>     # Subtest: 55 is not an empty plain object
worker1>     ok 8 - 55 is not an empty plain object
worker1>       ---
worker1>       duration_ms: 0.3106
worker1>       ...
worker1>     # Subtest: 'Test' is not an empty plain object
worker1>     ok 9 - 'Test' is not an empty plain object
worker1>       ---
worker1>       duration_ms: 0.2247
worker1>       ...
worker1>     # Subtest: new Object() is an empty plain object
worker1>     ok 10 - new Object() is an empty plain object
worker1>       ---
worker1>       duration_ms: 0.2681
worker1>       ...
worker1>     # Subtest: Object.create(null) is an empty plain object
worker1>     ok 11 - Object.create(null) is an empty plain object
worker1>       ---
worker1>       duration_ms: 0.2146
worker1>       ...
worker1>     1..11
worker1> ok 1 - isPlainObjectEmpty
worker1>   ---
worker1>   duration_ms: 7.0177
worker1>   type: 'suite'
worker1>   ...
worker1> 1..1
worker1> # tests 11
worker1> # suites 1
worker1> # pass 11
worker1> # fail 0
worker1> # cancelled 0
worker1> # skipped 0
worker1> # todo 0
worker1> # duration_ms 49.8298
worker3> TAP version 13
worker3> # Subtest: isPlainObject
worker3>     # Subtest: null is not a plain object
worker3>     ok 1 - null is not a plain object
worker3>       ---
worker3>       duration_ms: 1.5137
worker3>       ...
worker3>     # Subtest: undefined is not a plain object
worker3>     ok 2 - undefined is not a plain object
worker3>       ---
worker3>       duration_ms: 0.362
worker3>       ...
worker3>     # Subtest: {} is a plain object
worker3>     ok 3 - {} is a plain object
worker3>       ---
worker3>       duration_ms: 0.3961
worker3>       ...
worker3>     # Subtest: {test: 'a'} is a plain object
worker3>     ok 4 - {test: 'a'} is a plain object
worker3>       ---
worker3>       duration_ms: 0.2022
worker3>       ...
worker3>     # Subtest: [] is not a plain object
worker3>     ok 5 - [] is not a plain object
worker3>       ---
worker3>       duration_ms: 0.2894
worker3>       ...
worker3>     # Subtest: [1,2] is not a plain object
worker3>     ok 6 - [1,2] is not a plain object
worker3>       ---
worker3>       duration_ms: 0.197
worker3>       ...
worker3>     # Subtest: ()=>{} is not a plain object
worker3>     ok 7 - ()=>{} is not a plain object
worker3>       ---
worker3>       duration_ms: 0.2268
worker3>       ...
worker3>     # Subtest: 55 is not a plain object
worker3>     ok 8 - 55 is not a plain object
worker3>       ---
worker3>       duration_ms: 0.3035
worker3>       ...
worker3>     # Subtest: 'Test' is not a plain object
worker3>     ok 9 - 'Test' is not a plain object
worker3>       ---
worker3>       duration_ms: 0.2431
worker3>       ...
worker3>     # Subtest: new Object() is a plain object
worker3>     ok 10 - new Object() is a plain object
worker3>       ---
worker3>       duration_ms: 0.2797
worker3>       ...
worker3>     # Subtest: Object.create(null) is a plain object
worker3>     ok 11 - Object.create(null) is a plain object
worker3>       ---
worker3>       duration_ms: 0.1818
worker3>       ...
worker3>     1..11
worker3> ok 1 - isPlainObject
worker3>   ---
worker3>   duration_ms: 12.3032
worker3>   type: 'suite'
worker3>   ...
worker3> 1..1
worker3> # tests 11
worker3> # suites 1
worker3> # pass 11
worker3> # fail 0
worker3> # cancelled 0
worker3> # skipped 0
worker3> # todo 0
worker3> # duration_ms 64.9391
worker4> TAP version 13
worker4> # Subtest: deepFreeze
worker4>     # Subtest: Should Throw, argument 5 not an object
worker4>     ok 1 - Should Throw, argument 5 not an object
worker4>       ---
worker4>       duration_ms: 1.163
worker4>       ...
worker4>     # Subtest: Should Throw, argument "string" not an object
worker4>     ok 2 - Should Throw, argument "string" not an object
worker4>       ---
worker4>       duration_ms: 0.2882
worker4>       ...
worker4>     # Subtest: Should Freeze the object {}
worker4>     ok 3 - Should Freeze the object {}
worker4>       ---
worker4>       duration_ms: 0.252
worker4>       ...
worker4>     # Subtest: Should Freeze the object {a: 0}
worker4>     ok 4 - Should Freeze the object {a: 0}
worker4>       ---
worker4>       duration_ms: 1.4632
worker4>       ...
worker4>     # Subtest: Should Deep Freeze the object {a: {}}
worker4>     ok 5 - Should Deep Freeze the object {a: {}}
worker4>       ---
worker4>       duration_ms: 0.2133
worker4>       ...
worker4>     # Subtest: Should Deep Freeze the object {a: {a: {}}}
worker4>     ok 6 - Should Deep Freeze the object {a: {a: {}}}
worker4>       ---
worker4>       duration_ms: 0.2369
worker4>       ...
worker4>     # Subtest: Should Deep Freeze the object {a: {a: {}}, b:Buffer.from([1]) } and not throw.
worker4>     ok 7 - Should Deep Freeze the object {a: {a: {}}, b:Buffer.from([1]) } and not throw.
worker4>       ---
worker4>       duration_ms: 0.5188
worker4>       ...
worker4>     1..7
worker4> ok 1 - deepFreeze
worker4>   ---
worker4>   duration_ms: 8.2714
worker4>   type: 'suite'
worker4>   ...
worker4> 1..1
worker4> # tests 7
worker4> # suites 1
worker4> # pass 7
worker4> # fail 0
worker4> # cancelled 0
worker4> # skipped 0
worker4> # todo 0
worker4> # duration_ms 41.0767
worker2> TAP version 13
worker2> # Subtest: arrayToString
worker2>     # Subtest: [] should be []
worker2>     ok 1 - [] should be []
worker2>       ---
worker2>       duration_ms: 0.8047
worker2>       ...
worker2>     # Subtest: [,] should be [,]
worker2>     ok 2 - [,] should be [,]
worker2>       ---
worker2>       duration_ms: 0.1823
worker2>       ...
worker2>     # Subtest: [,,] should be [,,]
worker2>     ok 3 - [,,] should be [,,]
worker2>       ---
worker2>       duration_ms: 0.153
worker2>       ...
worker2>     # Subtest: [,0,0] should be [, 0, 0]
worker2>     ok 4 - [,0,0] should be [, 0, 0]
worker2>       ---
worker2>       duration_ms: 1.0969
worker2>       ...
worker2>     # Subtest: [0, ,0] should be [ 0, , 0]
worker2>     ok 5 - [0, ,0] should be [ 0, , 0]
worker2>       ---
worker2>       duration_ms: 0.1682
worker2>       ...
worker2>     # Subtest: [0, 'abc', 0] should be [ 0, 'abc', 0]
worker2>     ok 6 - [0, 'abc', 0] should be [ 0, 'abc', 0]
worker2>       ---
worker2>       duration_ms: 0.17
worker2>       ...
worker2>     # Subtest: 5 should throw TypeError('Expecting an array'), as 5 is not an array
worker2>     ok 7 - 5 should throw TypeError('Expecting an array'), as 5 is not an array
worker2>       ---
worker2>       duration_ms: 1.2051
worker2>       ...
worker2>     1..7
worker2> ok 1 - arrayToString
worker2>   ---
worker2>   duration_ms: 7.1491
worker2>   type: 'suite'
worker2>   ...
worker2> 1..1
worker2> # tests 7
worker2> # suites 1
worker2> # pass 7
worker2> # fail 0
worker2> # cancelled 0
worker2> # skipped 0
worker2> # todo 0
worker2> # duration_ms 34.1929

**Comment by connor4312** [comment]
huh, yea, that all looks fine 🤔 

Are you able to either share a repro case or grant me access to a repo where you see this happen so that I can reproduce and investigate more?

**Comment by khkiley** [comment]
This is it: brick-city/utils: A collection of utilities used by brick-city integration projects (github.com)<https://github.com/brick-city/utils>

**Comment by connor4312** [comment]
Thanks, I'll take a look this weekend

**Comment by khkiley** [comment]
Thank you.

Kurt

**Comment by connor4312** [comment]
Hm, this works for me. I would double check that you are in fact running the latest version of VS Code, since this sounds the same as an issue I fixed there a few months ago

<img width="449" alt="image" src="https://github.com/connor4312/nodejs-testing/assets/2230985/63ead184-929b-4447-8def-f891df45596a">

**Comment by NoelAbrahams** [comment]
I'm having the same problem. I'm posting a gif of what I'm seeing. In the scenario here I'm trying to fix a broken test case. After fixing and saving the file, when I try to re-run the tests from the top level, the test still shows as failed. This only turns green when I re-run the individual test.

![aaa2](https://github.com/connor4312/nodejs-testing/assets/1106823/70628f54-7ea0-4db8-bbbc-706bee229eb4)


Here's my VSCode setup:
![image](https://github.com/connor4312/nodejs-testing/assets/1106823/8d8c6d2c-9762-4568-8281-e748c599228b)

I have node 20.5.1 installed globally.

**Comment by khkiley** [comment]
Working now for me with the latest release, thank you!

K

**Comment by connor4312** [comment]
thanks for confirming, and yep I think this should be fixed now that we use a more reliable JSON stream to read out test results
